# Generated by Django 3.2.9 on 2021-12-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_art',
            field=models.ImageField(blank=True, null=True, upload_to='score_art/'),
        ),
    ]
